### ISSUE TITLE
Data process

### ISSUE THREAD

**Issue by JiamengLiu-PRC** [IvanEz/Red-GAN#2]
Dear sir

I am interested in your fancy work, and I want to implement your work into my work too. I have some questions to reimplement your work.

The first is that it seems that you using a 2D framework to implement this kind of work, I want to know whether this method works well in 3D data? And the second thing is how you convert the 3D image to 2D image?

**Comment by IvanEz** [comment]
Hi, we did not test the method on 3D data, thus difficult to say with certainty. To get 2D images we took 2D slices of the original 3D ones

**Comment by JiamengLiu-PRC** [comment]
Got it, thanks for your kind reply. And another thing is that does the synthesised 2D image slice stacked to 3D volume hold the same structure with origin 3D volumes.

Thanks!

**Comment by IvanEz** [comment]
Generally speaking, if one stacks 2D slices into 3D volumes, then most likely one gets misalignment along the stacking direction (as there is no enforcement of the alignment during 2D synthesis)

**Comment by JiamengLiu-PRC** [comment]
I will try your method in my tasks. And thanks very much.
